//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GergessShoppingWeb.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/GergessShoppingWeb")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/GergessShoppingWeb")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double amountPaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GergessShoppingWeb.ServiceReference1.Card cardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double amountPaid {
            get {
                return this.amountPaidField;
            }
            set {
                if ((this.amountPaidField.Equals(value) != true)) {
                    this.amountPaidField = value;
                    this.RaisePropertyChanged("amountPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GergessShoppingWeb.ServiceReference1.Card card {
            get {
                return this.cardField;
            }
            set {
                if ((object.ReferenceEquals(this.cardField, value) != true)) {
                    this.cardField = value;
                    this.RaisePropertyChanged("card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderDate {
            get {
                return this.orderDateField;
            }
            set {
                if ((object.ReferenceEquals(this.orderDateField, value) != true)) {
                    this.orderDateField = value;
                    this.RaisePropertyChanged("orderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                if ((object.ReferenceEquals(this.userIDField, value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/GergessShoppingWeb")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float cardNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cardTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cardName {
            get {
                return this.cardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cardNameField, value) != true)) {
                    this.cardNameField = value;
                    this.RaisePropertyChanged("cardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float cardNum {
            get {
                return this.cardNumField;
            }
            set {
                if ((this.cardNumField.Equals(value) != true)) {
                    this.cardNumField = value;
                    this.RaisePropertyChanged("cardNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cardType {
            get {
                return this.cardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.cardTypeField, value) != true)) {
                    this.cardTypeField = value;
                    this.RaisePropertyChanged("cardType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/GergessShoppingWeb")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desc {
            get {
                return this.descField;
            }
            set {
                if ((object.ReferenceEquals(this.descField, value) != true)) {
                    this.descField = value;
                    this.RaisePropertyChanged("desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imageURL {
            get {
                return this.imageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.imageURLField, value) != true)) {
                    this.imageURLField = value;
                    this.RaisePropertyChanged("imageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/GergessShoppingWeb")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int qtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderID {
            get {
                return this.orderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.orderIDField, value) != true)) {
                    this.orderIDField = value;
                    this.RaisePropertyChanged("orderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productID {
            get {
                return this.productIDField;
            }
            set {
                if ((object.ReferenceEquals(this.productIDField, value) != true)) {
                    this.productIDField = value;
                    this.RaisePropertyChanged("productID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qty {
            get {
                return this.qtyField;
            }
            set {
                if ((this.qtyField.Equals(value) != true)) {
                    this.qtyField = value;
                    this.RaisePropertyChanged("qty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDBServices")]
    public interface IDBServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/GetUserLogin", ReplyAction="http://tempuri.org/IDBServices/GetUserLoginResponse")]
        GergessShoppingWeb.ServiceReference1.User GetUserLogin(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/GetUserLogin", ReplyAction="http://tempuri.org/IDBServices/GetUserLoginResponse")]
        System.Threading.Tasks.Task<GergessShoppingWeb.ServiceReference1.User> GetUserLoginAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/GetUserID", ReplyAction="http://tempuri.org/IDBServices/GetUserIDResponse")]
        GergessShoppingWeb.ServiceReference1.User GetUserID(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/GetUserID", ReplyAction="http://tempuri.org/IDBServices/GetUserIDResponse")]
        System.Threading.Tasks.Task<GergessShoppingWeb.ServiceReference1.User> GetUserIDAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/InsertUser", ReplyAction="http://tempuri.org/IDBServices/InsertUserResponse")]
        int InsertUser(GergessShoppingWeb.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/InsertUser", ReplyAction="http://tempuri.org/IDBServices/InsertUserResponse")]
        System.Threading.Tasks.Task<int> InsertUserAsync(GergessShoppingWeb.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/InsertOrder", ReplyAction="http://tempuri.org/IDBServices/InsertOrderResponse")]
        int InsertOrder(GergessShoppingWeb.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/InsertOrder", ReplyAction="http://tempuri.org/IDBServices/InsertOrderResponse")]
        System.Threading.Tasks.Task<int> InsertOrderAsync(GergessShoppingWeb.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/GetProducts", ReplyAction="http://tempuri.org/IDBServices/GetProductsResponse")]
        System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Product> GetProducts(System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Product> product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/GetProducts", ReplyAction="http://tempuri.org/IDBServices/GetProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Product>> GetProductsAsync(System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Product> product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/CreateAnOrder", ReplyAction="http://tempuri.org/IDBServices/CreateAnOrderResponse")]
        int CreateAnOrder(System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Item> item, string userID, GergessShoppingWeb.ServiceReference1.Card card, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/CreateAnOrder", ReplyAction="http://tempuri.org/IDBServices/CreateAnOrderResponse")]
        System.Threading.Tasks.Task<int> CreateAnOrderAsync(System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Item> item, string userID, GergessShoppingWeb.ServiceReference1.Card card, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/GetOrders", ReplyAction="http://tempuri.org/IDBServices/GetOrdersResponse")]
        System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Order> GetOrders(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/GetOrders", ReplyAction="http://tempuri.org/IDBServices/GetOrdersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Order>> GetOrdersAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/GetOrderItems", ReplyAction="http://tempuri.org/IDBServices/GetOrderItemsResponse")]
        System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Item> GetOrderItems(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/GetOrderItems", ReplyAction="http://tempuri.org/IDBServices/GetOrderItemsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Item>> GetOrderItemsAsync(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/deleteOrder", ReplyAction="http://tempuri.org/IDBServices/deleteOrderResponse")]
        int deleteOrder(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServices/deleteOrder", ReplyAction="http://tempuri.org/IDBServices/deleteOrderResponse")]
        System.Threading.Tasks.Task<int> deleteOrderAsync(string orderID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBServicesChannel : GergessShoppingWeb.ServiceReference1.IDBServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServicesClient : System.ServiceModel.ClientBase<GergessShoppingWeb.ServiceReference1.IDBServices>, GergessShoppingWeb.ServiceReference1.IDBServices {
        
        public DBServicesClient() {
        }
        
        public DBServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GergessShoppingWeb.ServiceReference1.User GetUserLogin(string email, string pass) {
            return base.Channel.GetUserLogin(email, pass);
        }
        
        public System.Threading.Tasks.Task<GergessShoppingWeb.ServiceReference1.User> GetUserLoginAsync(string email, string pass) {
            return base.Channel.GetUserLoginAsync(email, pass);
        }
        
        public GergessShoppingWeb.ServiceReference1.User GetUserID(string ID) {
            return base.Channel.GetUserID(ID);
        }
        
        public System.Threading.Tasks.Task<GergessShoppingWeb.ServiceReference1.User> GetUserIDAsync(string ID) {
            return base.Channel.GetUserIDAsync(ID);
        }
        
        public int InsertUser(GergessShoppingWeb.ServiceReference1.User user) {
            return base.Channel.InsertUser(user);
        }
        
        public System.Threading.Tasks.Task<int> InsertUserAsync(GergessShoppingWeb.ServiceReference1.User user) {
            return base.Channel.InsertUserAsync(user);
        }
        
        public int InsertOrder(GergessShoppingWeb.ServiceReference1.Order order) {
            return base.Channel.InsertOrder(order);
        }
        
        public System.Threading.Tasks.Task<int> InsertOrderAsync(GergessShoppingWeb.ServiceReference1.Order order) {
            return base.Channel.InsertOrderAsync(order);
        }
        
        public System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Product> GetProducts(System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Product> product) {
            return base.Channel.GetProducts(product);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Product>> GetProductsAsync(System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Product> product) {
            return base.Channel.GetProductsAsync(product);
        }
        
        public int CreateAnOrder(System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Item> item, string userID, GergessShoppingWeb.ServiceReference1.Card card, double price) {
            return base.Channel.CreateAnOrder(item, userID, card, price);
        }
        
        public System.Threading.Tasks.Task<int> CreateAnOrderAsync(System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Item> item, string userID, GergessShoppingWeb.ServiceReference1.Card card, double price) {
            return base.Channel.CreateAnOrderAsync(item, userID, card, price);
        }
        
        public System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Order> GetOrders(string ID) {
            return base.Channel.GetOrders(ID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Order>> GetOrdersAsync(string ID) {
            return base.Channel.GetOrdersAsync(ID);
        }
        
        public System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Item> GetOrderItems(string orderID) {
            return base.Channel.GetOrderItems(orderID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GergessShoppingWeb.ServiceReference1.Item>> GetOrderItemsAsync(string orderID) {
            return base.Channel.GetOrderItemsAsync(orderID);
        }
        
        public int deleteOrder(string orderID) {
            return base.Channel.deleteOrder(orderID);
        }
        
        public System.Threading.Tasks.Task<int> deleteOrderAsync(string orderID) {
            return base.Channel.deleteOrderAsync(orderID);
        }
    }
}
